spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT} # environment variable
  datasource:
    url: ${spring.datasource.url} # secret from azure key vault
    username: ${spring.datasource.username} # secret from azure key vault
    password: ${spring.datasource.password} # secret from azure key vault
  jpa:
    hibernate:
      ddl-auto: none